[package]
name = "nlf-core"
version = "0.1.0"
edition = "2024"
default-run = "nlf"

[lib]
name = "nlf_core"

[dependencies]
clap = { version = "4.5.48", features = ["derive"] }
ctor = "0.6.1"
indexmap = { version = "2.11.4", features = ["serde"] }
inline_colorization = "0.1.6"
lazy_static = "1.5.0"
libloading = "0.9.0"
parking_lot = "0.12.5"
rand = "0.9.2"
rayon = "1.11.0"
reqwest = { version = "0.12.14", features = ["blocking", "json"] }
rust-embed = { version = "8.9.0", features = ["include-exclude"]}
serde = { version = "1.0.228", features = ["derive", "rc"] }
serde_json = { version = "1.0.145", features = ["preserve_order"] }
strum = { version = "0.27.2", features = ["derive"] }
# types = { path = "./types"}
nlf-shared = { path = "../shared"}
nlf-macros = { path = "../macros" }
smallvec = { version = "1.15.1", features = ["union"] }
ron = "0.12.1"

[[bin]]
name = "nlf"
path = "src/main.rs"